### ISSUE TITLE
Tensorflow.python.framework.errors_impl.InvalidArgumentError: indices [5555 ， 6] =-1 is not in [0, 11495).

### ISSUE THREAD

**Issue by BuildForOcean** [fkong7/MeshDeformNet#12]
Hello, have you ever encountered this problem in the process of debugging train_gcn.py: indices [555， 6] =-1 is not in [0, 11495).
When the program runs to the training section, the specific error message is as follows:
Epoch 1/500.
Traceback (most recent call last):
File "/ Projects/MeshDeformNet-main/train_gcn.py", line 344, in < module >.
Callbacks=call_backs).
File "/ root/anaconda3/envs/meshdeformnet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit.
Steps_name='steps_per_epoch').
File "/ root/anaconda3/envs/meshdeformnet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration.
Batch_outs = f (actual_inputs).
File "/ root/anaconda3/envs/meshdeformnet/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in _ _ call__.
Run_metadata=self.run_metadata).
File "/ root/anaconda3/envs/meshdeformnet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in _ _ call__.
Run_metadata_ptr).
Tensorflow.python.framework.errors_impl.InvalidArgumentError: indices [5555 ， 6] =-1 is not in [0, 11495).
[[{{node loss/lambda_loss/GatherV2_7}}]].

It has been bothering me for many days. I would appreciate it if I could solve it.

**Comment by fkong7** [comment]
Hello, it looks similar to the error encountered in another issue #5. Does the discussion there help?

**Comment by BuildForOcean** [comment]
> Hello, it looks similar to the error encountered in another issue #5. Does the discussion there help?

Thank you very much. I have benefited a lot from the discussion [[here.]](https://github.com/fkong7/MeshDeformNet/issues/5) It has been very helpful. Thank you very much.

**Comment by BuildForOcean** [comment]
> Hello, it looks similar to the error encountered in another issue #5. Does the discussion there help?

Thank you very much. I have benefited a lot from the discussion [[here.]](https://github.com/fkong7/MeshDeformNet/issues/5) It has been very helpful. Thank you very much.
